# Question 7
select CARTON_ID,MAX(LEN * WIDTH * HEIGHT) as carton_vol
from carton
WHERE (LEN * WIDTH * HEIGHT) > 
(
    select SUM(b.LEN * b.WIDTH * b.HEIGHT * a.PRODUCT_QUANTITY) as carton_vol
    from order_items a
    inner JOIN product b on a.PRODUCT_ID = b.PRODUCT_ID
    where a.ORDER_ID = 10006
);
# Question 8
SELECT 
    OI.ORDER_ID,
    C.CUSTOMER_ID,
    CONCAT(C.CUSTOMER_FNAME, ' ', C.CUSTOMER_LNAME) AS 'CUSTOMER_FULL_NAME',
    SUM(OI.PRODUCT_QUANTITY) AS 'TOTAL_ORDER_QTY'
FROM
    online_customer C
        INNER JOIN
    ORDER_HEADER OH ON C.CUSTOMER_ID = OH.CUSTOMER_ID
        AND OH.ORDER_STATUS = 'Shipped'
        INNER JOIN
    order_items OI ON OH.ORDER_ID = OI.ORDER_ID
GROUP BY OI.ORDER_ID
HAVING TOTAL_ORDER_QTY > 10; 

# Question 9
SELECT 
    OI.ORDER_ID,
    C.CUSTOMER_ID,
    CONCAT(C.CUSTOMER_FNAME, ' ', C.CUSTOMER_LNAME) AS 'CUSTOMER_FULL_NAME',
    SUM(OI.PRODUCT_QUANTITY) AS 'TOTAL_QUANTITY'
FROM
    online_customer C
        INNER JOIN
    ORDER_HEADER OH ON C.CUSTOMER_ID = OH.CUSTOMER_ID
        INNER JOIN
    order_items OI ON OH.ORDER_ID = OI.ORDER_ID
WHERE
    OH.ORDER_ID > 10060
        AND OH.ORDER_STATUS = 'Shipped'
GROUP BY OI.ORDER_ID; 
# Question 10

SELECT B.PRODUCT_CLASS_DESC,SUM(C.PRODUCT_QUANTITY) TOTAL_QUANTITY,
SUM(C.PRODUCT_QUANTITY * A.PRODUCT_PRICE) AS TOTAL_VALUE
FROM product A
INNER JOIN product_class B ON A.PRODUCT_CLASS_CODE = B.PRODUCT_CLASS_CODE
INNER JOIN order_items C ON A.PRODUCT_ID = C.PRODUCT_ID
INNER JOIN order_header D ON C.ORDER_ID = D.ORDER_ID
INNER JOIN online_customer E ON D.CUSTOMER_ID = E.CUSTOMER_ID
INNER JOIN address F ON E.ADDRESS_ID = F.ADDRESS_ID
WHERE F.COUNTRY NOT IN ('INDIA','USA') AND D.ORDER_STATUS = 'SHIPPED'
GROUP BY B.PRODUCT_CLASS_DESC
ORDER BY TOTAL_QUANTITY DESC
LIMIT 1;